[build]
  functions = "netlify/functions"
  command = "npm install"
  publish = "public"

[functions]
  external_node_modules = ["chrome-aws-lambda", "puppeteer-core"]
  included_files = ["node_modules/chrome-aws-lambda/**/*"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  publish = "public"
  port = 8888
  autoLaunch = true 